#!/bin/csh -f
if (-f a.junk) \rm a.junk
../../bin/focmec << EOT > a.junk
focmec_R2.0.out
Event 8703270729 2.0 relative errors
\* Comment is previous line: Input file for focmec is next
8703270729.dat
	correct file  [y]
y	relative weighting..[n] 
0.1	threshold for relative weighting
2.0	allowed P polarity erors..[0]
	exit after this many acceptable solutions...[100]
	minimum B trend  [0]
	B increment  [5]
	maximum B trend  [355]
	min B plunge..[0]
	increment  [5]
	maximum..[90]
	minimum A angle..[0]
	increment  [5]
	maximum  [85]
EOT
mv focmec.lst focmec_R2.0.lst
