#!/bin/csh -f
# This is a test of the program ttimes that produces traveltimes and
#  takeoff angles for hypocenter-station geometries in either ak135 or iasp91.
# The output is three files: ttimes.term (terminal output if run without
#  the script) plus ttimes_ak135.lst and ttimes_iasp91.lst.  Copies of these
#  filoes are in ../doc/tests-doc/.
# The same commands are used in program Focmec_prep in this pckage
#
if ( -f ak135.term) \rm ttimes.term
../bin/ttimes << EOT1 > ttimes.term
y
../lib/ak135
all

n
515.
78.
-10.
300.
50.
150.
-10.
-10.
EOT1
if ($status != 0) exit
mv ttimes.lst ttimes_ak135.lst
../bin/ttimes << EOT2 >> ttimes.term 
n
../lib/iasp91
all

n
515.
78.
-10.
300.
50.
150.
-10.
-10.
EOT2
if ($status != 0) exit
cat ttimes.lst  > ttimes_iasp91.lst
rm ttimes.lst
cat run_ttimes >> ttimes.term
