#!/bin/csh -f
if (-f a.junk) \rm a.junk
../../bin/focmec << EOT > a.junk
/*  FOCMEC .out file [focmec.out]
focmec_all.out		Output file name [focmec.out]
Sakhalin: 8 BB stations + 189 NEIC P polarities (TOL in both)
/*  Previous line comment (up to 80 char) Next line input file [focmec.iknp]
focmec_all.inp
	correct file  [y]
n	use emergent arrivals? ..[y]
n	relative weighting..[n]
y	Total polarity option
27	allowed polarity erors..[0]
1.83	vp/vs ratio..[1.732]
0.5	maximum allowed log10 of ratio..[0.6]
0	numer of allowed ratio errors
        lower-limit cutoff for P radiation factor..[0.05]
        lower-limit cutoff for S radiation factor..[0.15]
	exit after this many acceptable solutions...[100]
	minimum B trend  [0]
	B increment  [5]
	maximum B trend  [355]
	min B plunge..[0]
	increment  [5]
	maximum..[90]
	minimum A angle..[0]
	increment  [5]
	maximum  [85]
EOT
mv focmec.lst focmec_all.lst
