#!/bin/csh -f
if (-f a.junk) \rm a.junk
../../bin/focmec << EOT > a.junk
/*  FOCMEC .out file [focmec.out]
focmec_all-CMTFR.out		Output file name [focmec.out]
Sakhalin: 8 BB stations + 189 NEIC first motions: CMT sol. fixed
/*  Previous line comment (up to 80 char) Next line input file [focmec.iknp]
focmec_all.inp
	correct file  [y]
n	Use emergent arrivals?..[y]
y	relative weighting..[n]
0.1	threshold for weighting
y	Total polarity option
50	allowed polarity erors..[0]
1.83	vp/vs ratio..[1.732]
0.5	maximum allowed log10 of ratio..[0.6]
16	numer of allowed ratio errors
        lower-limit cutoff for P radiation factor..[0.05]
        lower-limit cutoff for S radiation factor..[0.15]
	exit after this many acceptable solutions...[100]
229.65	minimum B trend  [0]
5.	B increment  [5]
229.65	maximum B trend  [355]
24.85	min B plunge..[0]
5	increment  [5]
24.85	maximum..[90]
15.1	minimum A angle..[0]
5	increment  [5]
15.1	maximum  [85]
EOT
mv focmec.lst focmec_all-CMTFR.lst
