#!/bin/csh -f
if ( -f ak135.term) \rm ak135.term
../bin/remodl ak135> ak135.term
../bin/setbrn >> ak135.term
if ( -f iasp91.term) \rm iasp91.term
../bin/remodl iasp91 > iasp91.term
../bin/setbrn >> iasp91.term
mkdir -p stuff
\mv setb* remod* stuff
